title: Tan Wei Chiong
description: An aspiring data scientist and former mathematics educator. My academic interests lie in graph theory and its applications to natural language processing.
logo: /assets/profile_photo_github.png
theme: jekyll-theme-minimal
