title: Tan Wei Chiong
description: The satisfaction of delivering a well-crafted story, woven from complex concepts and data, never gets old.
logo: /assets/profile_photo_github.png
theme: jekyll-theme-minimal
